//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Paradox.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ParadoxParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IParadoxListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] ParadoxParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] ParadoxParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] ParadoxParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] ParadoxParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] ParadoxParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] ParadoxParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] ParadoxParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] ParadoxParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.contents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContents([NotNull] ParadoxParser.ContentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.contents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContents([NotNull] ParadoxParser.ContentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParadoxParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] ParadoxParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParadoxParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] ParadoxParser.ListContext context);
}
